---
version: '2'

services:
  nginx:
    build:
      context: .
    container_name: infra_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d/:/etc/nginx/conf.d/
    restart: unless-stopped
